import { readFileSync, existsSync, readdirSync } from 'fs'
import { execSync } from 'child_process'
import { join, basename, resolve } from 'path'
import bundledRegistry from '@/lib/agents.json'
import type { Agent } from '@/lib/types'

/**
 * Extract a JSON object or array from CLI output that may contain
 * trailing non-JSON content (e.g. ANSI-colored plugin log lines).
 * Strips ANSI escape sequences before parsing.
 */
function extractJson(raw: string): unknown {
  // Strip ANSI escape codes (e.g. \x1b[35m, \x1b[39m)
  const clean = raw.replace(/\x1b\[[0-9;]*m/g, '')
  // Try direct parse first
  try { return JSON.parse(clean) } catch {}
  // Find the JSON boundary -- first [ or { to its matching closer
  const arrStart = clean.indexOf('[')
  const objStart = clean.indexOf('{')
  const start = arrStart === -1 ? objStart : objStart === -1 ? arrStart : Math.min(arrStart, objStart)
  if (start === -1) throw new Error('No JSON in CLI output')
  // Walk forward counting brackets to find the matching close
  const opener = clean[start]
  const closer = opener === '[' ? ']' : '}'
  let depth = 0
  let inString = false
  let escape = false
  for (let i = start; i < clean.length; i++) {
    const ch = clean[i]
    if (escape) { escape = false; continue }
    if (ch === '\\' && inString) { escape = true; continue }
    if (ch === '"') { inString = !inString; continue }
    if (inString) continue
    if (ch === opener) depth++
    else if (ch === closer) {
      depth--
      if (depth === 0) return JSON.parse(clean.slice(start, i + 1))
    }
  }
  throw new Error('Unterminated JSON in CLI output')
}

/** Raw agent data from JSON (everything except runtime-loaded soul and crons) */
export type AgentEntry = Omit<Agent, 'soul' | 'crons'>

/** Color palette assigned to auto-discovered agents */
const DISCOVER_COLORS = [
  '#f5c518', '#a855f7', '#3b82f6', '#22c55e', '#f97316',
  '#eab308', '#14b8a6', '#60a5fa', '#f59e0b', '#94a3b8',
  '#06b6d4', '#ec4899', '#84cc16', '#8b5cf6', '#ef4444',
]

// ---------------------------------------------------------------------------
// Registry cache (avoids repeated execSync CLI calls on every API request)
// ---------------------------------------------------------------------------

let _registryCache: { data: AgentEntry[]; ts: number } | null = null
const REGISTRY_CACHE_TTL = 60_000 // 60 seconds

// ---------------------------------------------------------------------------
// Heading / identity extraction helpers (exported for testing)
// ---------------------------------------------------------------------------

/**
 * Parse a SOUL.md heading into a clean agent name and optional title.
 *
 * Handles all observed heading formats:
 *   "# SOUL.md -- VERA"                 -> name "VERA"
 *   "# SOUL.md -- KAZE, Flight Research Agent" -> name "KAZE", title "Flight Research Agent"
 *   "# ECHO -- Community Voice Monitor" -> name "ECHO", title "Community Voice Monitor"
 *   "# SOUL.md - Who You Are"          -> name null (not a useful agent name)
 *   "# QUILL -- Herald's Content Writer" -> name "QUILL", title "Herald's Content Writer"
 */
export function parseSoulHeading(content: string): { name: string | null; title: string | null } {
  const match = content.match(/^#\s+(.+)/m)
  if (!match) return { name: null, title: null }

  let heading = match[1].trim()

  // Strip "SOUL.md -- ", "SOUL.md - ", "SOUL.md:" prefixes
  heading = heading.replace(/^SOUL\.md\s*[—–\-:]\s*/i, '')

  // If the heading is generic (e.g. "Who You Are"), it's not a useful agent name
  if (/^who\s+you\s+are/i.test(heading)) return { name: null, title: null }

  // Split on em-dash / en-dash to separate name from description
  const dashParts = heading.split(/\s*[—–]\s*/)
  const nameAndMaybeTitle = dashParts[0].trim()
  const descAfterDash = dashParts.length > 1 ? dashParts.slice(1).join(' — ').trim() : null

  // The name might contain a comma: "LUMEN, SEO Team Director"
  const commaParts = nameAndMaybeTitle.split(/,\s*/)
  const name = commaParts[0].trim() || null
  const titleFromComma = commaParts.length > 1 ? commaParts.slice(1).join(', ').trim() : null

  const title = titleFromComma || descAfterDash || null
  return { name, title }
}

/**
 * Parse an IDENTITY.md file for agent name and emoji.
 *
 * Expected format (generated by OpenClaw bootstrap):
 *   - **Name:** Atlas
 *   - **Emoji:** robot
 */
export function parseIdentity(content: string): { name: string | null; emoji: string | null; avatar: string | null } {
  // Normalize literal \n sequences to actual newlines (malformed IDENTITY.md files)
  const normalized = content.replace(/\\n/g, '\n')
  const nameMatch = normalized.match(/\*\*Name:\*\*\s*(.+)/i)
  const emojiMatch = normalized.match(/\*\*Emoji:\*\*\s*(\S+)/i)
  const avatarMatch = normalized.match(/\*\*Avatar:\*\*\s*(.+)/i)
  let name = nameMatch ? nameMatch[1].trim() : null
  let emoji = emojiMatch ? emojiMatch[1].trim() : null
  let avatar = avatarMatch ? avatarMatch[1].trim() : null
  // Strip markdown emphasis wrappers and placeholder text
  if (name) {
    name = name.replace(/^_+|_+$/g, '').trim()
    if (/pick something|fill this in/i.test(name) || name === '') name = null
  }
  if (emoji) {
    emoji = emoji.replace(/^_+|_+$/g, '').trim()
    if (/pick one|pick something|your signature/i.test(emoji) || emoji === '' || emoji.startsWith('(')) emoji = null
  }
  if (avatar) {
    avatar = avatar.replace(/^_+|_+$/g, '').trim()
    if (/workspace-relative|data URI/i.test(avatar) || avatar === '') avatar = null
    // Strip trailing parenthetical notes
    if (avatar) avatar = avatar.replace(/\s*\(.*\)\s*$/, '').trim()
    if (avatar === '') avatar = null
  }
  return { name, emoji, avatar }
}

/**
 * Convert a directory slug to a display name: "my-agent" -> "My Agent"
 */
function slugToName(slug: string): string {
  return slug
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

/**
 * Read a file and return its content, or null on any error.
 */
function safeRead(filePath: string): string | null {
  try {
    if (!existsSync(filePath)) return null
    return readFileSync(filePath, 'utf-8')
  } catch {
    return null
  }
}

/**
 * Scan a directory for sub-agent .md files (e.g. sub-agents/QUILL.md, members/WRITER.md).
 * Returns an array of { fileName, content } for each .md file found.
 */
function scanSubAgentDir(dirPath: string): { fileName: string; content: string }[] {
  if (!existsSync(dirPath)) return []
  try {
    return readdirSync(dirPath)
      .filter(f => f.endsWith('.md'))
      .map(f => {
        const content = safeRead(join(dirPath, f))
        return content ? { fileName: f, content } : null
      })
      .filter((x): x is { fileName: string; content: string } => x !== null)
  } catch {
    return []
  }
}

/**
 * Scan a parent agent directory for child subdirectories containing SOUL.md.
 * Skips sub-agents/ and members/ (already handled by scanSubAgentDir).
 */
function scanSubdirAgents(parentDir: string): { dirName: string; content: string }[] {
  if (!existsSync(parentDir)) return []
  try {
    return readdirSync(parentDir, { withFileTypes: true })
      .filter(e => e.isDirectory() && e.name !== 'sub-agents' && e.name !== 'members')
      .map(e => {
        const content = safeRead(join(parentDir, e.name, 'SOUL.md'))
        return content ? { dirName: e.name, content } : null
      })
      .filter((x): x is { dirName: string; content: string } => x !== null)
  } catch {
    return []
  }
}

// ---------------------------------------------------------------------------
// Auto-discovery
// ---------------------------------------------------------------------------

/**
 * Auto-discover agents from $WORKSPACE_PATH.
 *
 * Scans the workspace for:
 *   - IDENTITY.md at root (for root agent name/emoji)
 *   - SOUL.md at root (root orchestrator)
 *   - agents/<dir>/SOUL.md (top-level agents)
 *   - agents/<dir>/sub-agents/*.md (nested sub-agents)
 *   - agents/<dir>/members/*.md (team member agents)
 *
 * Returns null if nothing can be discovered.
 */
function discoverAgents(workspacePath: string): AgentEntry[] | null {
  const agentsDir = join(workspacePath, 'agents')
  const rootSoulPath = join(workspacePath, 'SOUL.md')
  const identityPath = join(workspacePath, 'IDENTITY.md')
  const hasRoot = existsSync(rootSoulPath)

  // Scan agents/ directory for all subdirectories (even without SOUL.md, may have sub-agents)
  let allAgentDirs: string[] = []
  if (existsSync(agentsDir)) {
    try {
      const entries = readdirSync(agentsDir, { withFileTypes: true })
      allAgentDirs = entries.filter(e => e.isDirectory()).map(e => e.name)
    } catch {}
  }

  // Need at least a root or agent directories to discover
  if (!hasRoot && allAgentDirs.length === 0) return null

  const discovered: AgentEntry[] = []
  let colorIndex = 0
  const directReportIds: string[] = []

  // --- Root agent ---
  let rootId = 'main'
  let rootName = 'Main'
  let rootEmoji = '\u{1F916}'
  let rootAvatar: string | null = null

  if (hasRoot) {
    // Try IDENTITY.md first (most reliable source for name/emoji)
    const identityContent = safeRead(identityPath)
    if (identityContent) {
      const identity = parseIdentity(identityContent)
      if (identity.name) {
        rootName = identity.name
        rootId = identity.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
      }
      if (identity.emoji) rootEmoji = identity.emoji
      if (identity.avatar && existsSync(join(workspacePath, identity.avatar))) {
        rootAvatar = identity.avatar
      }
    }

    // Fall back to SOUL.md heading if IDENTITY.md didn't provide a name
    if (rootName === 'Main') {
      const soulContent = safeRead(rootSoulPath)
      if (soulContent) {
        const parsed = parseSoulHeading(soulContent)
        if (parsed.name) {
          rootName = parsed.name
          rootId = parsed.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'main'
        }
      }
    }

    discovered.push({
      id: rootId,
      name: rootName,
      title: 'Orchestrator',
      reportsTo: null,
      directReports: directReportIds, // populated below
      soulPath: 'SOUL.md',
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: rootEmoji,
      tools: ['read', 'write', 'exec', 'message'],
      model: null,
      memoryPath: null,
      avatarUrl: rootAvatar ? `/api/avatar/${rootId}` : null,
      description: 'Top-level orchestrator.',
    })

    // We'll fill directReportIds as we discover agents below
    for (const dirName of allAgentDirs) {
      if (dirName === rootId) continue // root-matching dir scanned in main loop
      const hasSoul = existsSync(join(agentsDir, dirName, 'SOUL.md'))
      const hasSubAgents = existsSync(join(agentsDir, dirName, 'sub-agents'))
      const hasMembers = existsSync(join(agentsDir, dirName, 'members'))
      if (hasSoul || hasSubAgents || hasMembers) {
        directReportIds.push(dirName)
      }
    }
  }

  // --- Top-level agents ---
  for (const dirName of allAgentDirs) {
    // Root-matching directory: scan for sub-agents but don't create a duplicate root entry
    if (hasRoot && dirName === rootId) {
      const rootAgentDir = join(agentsDir, dirName)
      const rootSubFiles = [
        ...scanSubAgentDir(join(rootAgentDir, 'sub-agents')),
        ...scanSubAgentDir(join(rootAgentDir, 'members')),
      ]
      const rootSubIds = new Set<string>()
      for (const sub of rootSubFiles) {
        const subId = `${rootId}-${basename(sub.fileName, '.md').toLowerCase()}`
        rootSubIds.add(subId)
        directReportIds.push(subId)
        const subParsed = parseSoulHeading(sub.content)
        const subName = subParsed.name || slugToName(basename(sub.fileName, '.md'))
        const subTitle = subParsed.title || 'Agent'
        discovered.push({
          id: subId,
          name: subName,
          title: subTitle,
          reportsTo: rootId,
          directReports: [],
          soulPath: null,
          voiceId: null,
          color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
          emoji: subName.charAt(0).toUpperCase(),
          tools: ['read', 'write'],
          model: null,
          memoryPath: null,
          avatarUrl: null,
          description: `${subName} agent.`,
        })
      }

      for (const sub of scanSubdirAgents(rootAgentDir)) {
        const subId = `${rootId}-${sub.dirName}`
        if (rootSubIds.has(subId)) continue
        directReportIds.push(subId)
        const subParsed = parseSoulHeading(sub.content)
        const subName = subParsed.name || slugToName(sub.dirName)
        const subTitle = subParsed.title || 'Agent'
        discovered.push({
          id: subId,
          name: subName,
          title: subTitle,
          reportsTo: rootId,
          directReports: [],
          soulPath: `agents/${rootId}/${sub.dirName}/SOUL.md`,
          voiceId: null,
          color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
          emoji: subName.charAt(0).toUpperCase(),
          tools: ['read', 'write'],
          model: null,
          memoryPath: null,
          avatarUrl: null,
          description: `${subName} agent.`,
        })
      }
      continue
    }

    const soulFile = join(agentsDir, dirName, 'SOUL.md')
    const hasSoul = existsSync(soulFile)
    const subAgentsDir = join(agentsDir, dirName, 'sub-agents')
    const membersDir = join(agentsDir, dirName, 'members')
    const hasSubAgents = existsSync(subAgentsDir)
    const hasMembers = existsSync(membersDir)

    // Skip directories with nothing useful
    if (!hasSoul && !hasSubAgents && !hasMembers) continue

    let name = slugToName(dirName)
    let title = 'Agent'
    const subAgentIds: string[] = []

    // Parse SOUL.md for name and title
    if (hasSoul) {
      const content = safeRead(soulFile)
      if (content) {
        const parsed = parseSoulHeading(content)
        if (parsed.name) name = parsed.name
        if (parsed.title) title = parsed.title

        // Also check for Role: or Title: lines as fallback
        if (title === 'Agent') {
          const roleMatch = content.match(/^##\s*Role\b/mi)
          if (roleMatch) {
            // Try to get first line after ## Role
            const afterRole = content.slice(roleMatch.index! + roleMatch[0].length)
            const firstLine = afterRole.match(/\n\s*\n(.+)/)?.[1]?.trim()
            // Don't use long role descriptions as titles
            if (firstLine && firstLine.length < 80) title = firstLine
          }
        }
      }
    }

    // Discover sub-agents (sub-agents/ and members/ directories)
    const subAgentFiles = [
      ...scanSubAgentDir(subAgentsDir),
      ...scanSubAgentDir(membersDir),
    ]

    for (const sub of subAgentFiles) {
      const subId = `${dirName}-${basename(sub.fileName, '.md').toLowerCase()}`
      subAgentIds.push(subId)

      const subParsed = parseSoulHeading(sub.content)
      const subName = subParsed.name || slugToName(basename(sub.fileName, '.md'))
      const subTitle = subParsed.title || 'Agent'

      discovered.push({
        id: subId,
        name: subName,
        title: subTitle,
        reportsTo: dirName,
        directReports: [],
        soulPath: null, // sub-agents use non-standard paths, soul loaded differently
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: subName.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        model: null,
        memoryPath: null,
        avatarUrl: null,
        description: `${subName} agent.`,
      })
    }

    // Discover subdirectory agents (child dirs with SOUL.md)
    const subdirAgents = scanSubdirAgents(join(agentsDir, dirName))
    const existingSubIds = new Set(subAgentIds)
    for (const sub of subdirAgents) {
      const subId = `${dirName}-${sub.dirName}`
      if (existingSubIds.has(subId)) continue
      subAgentIds.push(subId)
      const subParsed = parseSoulHeading(sub.content)
      const subName = subParsed.name || slugToName(sub.dirName)
      const subTitle = subParsed.title || 'Agent'
      discovered.push({
        id: subId,
        name: subName,
        title: subTitle,
        reportsTo: dirName,
        directReports: [],
        soulPath: `agents/${dirName}/${sub.dirName}/SOUL.md`,
        voiceId: null,
        color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
        emoji: subName.charAt(0).toUpperCase(),
        tools: ['read', 'write'],
        model: null,
        memoryPath: null,
        avatarUrl: null,
        description: `${subName} agent.`,
      })
    }

    discovered.push({
      id: dirName,
      name,
      title,
      reportsTo: hasRoot ? rootId : null,
      directReports: subAgentIds,
      soulPath: hasSoul ? `agents/${dirName}/SOUL.md` : null,
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji: name.charAt(0).toUpperCase(),
      tools: ['read', 'write'],
      model: null,
      memoryPath: null,
      avatarUrl: null,
      description: `${name} agent.`,
    })
  }

  return discovered.length > 0 ? discovered : null
}

// ---------------------------------------------------------------------------
// CLI-based multi-workspace discovery (openclaw agents list)
// ---------------------------------------------------------------------------

/**
 * Raw entry from `openclaw agents list --json`.
 */
interface CliAgentEntry {
  id: string
  identityName?: string
  identityEmoji?: string
  model?: string
  workspace?: string
  isDefault?: boolean
}

/**
 * Call `openclaw agents list --json` and return parsed entries.
 * Returns null on any failure (CLI not found, bad JSON, timeout).
 */
export function listCliAgents(openclawBin: string): CliAgentEntry[] | null {
  try {
    const raw = execSync(`${openclawBin} agents list --json`, {
      encoding: 'utf-8',
      timeout: 10000,
    })
    const parsed = extractJson(raw)
    const agents: unknown[] = Array.isArray(parsed) ? parsed : []
    if (agents.length === 0) return null
    return agents as CliAgentEntry[]
  } catch {
    return null
  }
}

/**
 * Merge CLI-discovered agents into the registry.
 *
 * Agents under the same .openclaw installation as the primary workspace
 * are children of the root agent. Agents from entirely different installations
 * are added as top-level peers.
 */
function mergeExtraWorkspaces(
  existing: AgentEntry[],
  cliAgents: CliAgentEntry[],
  primaryWorkspace: string,
): AgentEntry[] {
  const existingIds = new Set(existing.map(a => a.id))
  const rootAgent = existing.find(a => a.reportsTo === null)
  const rootId = rootAgent?.id ?? null
  let colorIndex = existing.length

  // Determine the .openclaw root dir from the primary workspace
  const openclawRoot = resolve(primaryWorkspace, '..')

  const added: AgentEntry[] = []

  for (const cli of cliAgents) {
    const ws = cli.workspace
    if (!ws || ws === primaryWorkspace) continue
    if (existingIds.has(cli.id)) continue

    // Check if this agent's workspace is under the same .openclaw installation
    const isSameInstallation = ws.startsWith(openclawRoot + '/')

    // Read SOUL.md and IDENTITY.md from the agent's workspace
    const soulContent = safeRead(join(ws, 'SOUL.md'))
    const identityContent = safeRead(join(ws, 'IDENTITY.md'))

    // Resolve name: CLI identity > parsed IDENTITY.md > slug
    let name = cli.identityName || null
    let emoji = cli.identityEmoji || null
    let avatarFile: string | null = null
    let title = 'Agent'
    let description = ''

    if (identityContent) {
      const parsed = parseIdentity(identityContent)
      if (!name && parsed.name) name = parsed.name
      if (!emoji && parsed.emoji) emoji = parsed.emoji
      if (parsed.avatar && existsSync(join(ws, parsed.avatar))) {
        avatarFile = parsed.avatar
      }
    }
    if (!name) name = slugToName(cli.id)
    if (!emoji) emoji = name.charAt(0).toUpperCase()

    if (soulContent) {
      const soulParsed = parseSoulHeading(soulContent)
      if (soulParsed.title) title = soulParsed.title
      // Extract first paragraph as description
      const descMatch = soulContent.match(/\n\n([^\n#].{10,})/m)
      if (descMatch) description = descMatch[1].trim().slice(0, 120)
    }
    if (!description) description = `${name} agent.`

    // Determine tools from workspace files
    const toolsPath = join(ws, 'TOOLS.md')
    const toolsContent = safeRead(toolsPath)
    let tools = ['read', 'write']
    if (toolsContent) {
      const toolMatches = toolsContent.match(/^-\s+(\w+)/gm)
      if (toolMatches && toolMatches.length > 0) {
        tools = toolMatches.map(m => m.replace(/^-\s+/, ''))
      }
    }

    const agent: AgentEntry = {
      id: cli.id,
      name,
      title,
      reportsTo: isSameInstallation && rootId ? rootId : null,
      directReports: [],
      soulPath: soulContent ? 'SOUL.md' : null,
      voiceId: null,
      color: DISCOVER_COLORS[colorIndex++ % DISCOVER_COLORS.length],
      emoji,
      avatarUrl: avatarFile ? `/api/avatar/${cli.id}` : null,
      tools,
      model: cli.model || null,
      memoryPath: null,
      description,
    }

    added.push(agent)
    existingIds.add(cli.id)

    // Register as direct report of root agent
    if (isSameInstallation && rootAgent) {
      rootAgent.directReports.push(cli.id)
    }
  }

  return [...existing, ...added]
}

/**
 * Enrich filesystem-discovered agents with model data from CLI output.
 *
 * All agents in a workspace share the CLI agent's configured model.
 * CLI agents are matched to discovered agents by workspace path.
 */
function enrichModelsFromCli(
  agents: AgentEntry[],
  cliAgents: CliAgentEntry[],
  primaryWorkspace: string,
): void {
  // Find CLI agent(s) for the primary workspace -- take the default or first match
  const primaryCli = cliAgents.find(c => c.workspace === primaryWorkspace && c.isDefault)
    || cliAgents.find(c => c.workspace === primaryWorkspace)

  // Fix root agent ID to match CLI ID (filesystem may derive different ID from IDENTITY.md
  // but CLI uses the configured ID -- crons reference CLI IDs so we must align)
  if (primaryCli) {
    const root = agents.find(a => a.reportsTo === null)
    if (root && primaryCli.id && root.id !== primaryCli.id) {
      const oldId = root.id
      root.id = primaryCli.id
      if (primaryCli.identityName) root.name = primaryCli.identityName
      if (primaryCli.identityEmoji) root.emoji = primaryCli.identityEmoji
      // Update children's reportsTo and directReports references
      for (const a of agents) {
        if (a.reportsTo === oldId) a.reportsTo = primaryCli.id
        a.directReports = a.directReports.map(id => id === oldId ? primaryCli.id : id)
      }
    }
  }

  // Apply per-agent models from CLI (each CLI agent may have a distinct model)
  for (const cli of cliAgents) {
    if (cli.model) {
      const agent = agents.find(a => a.id === cli.id)
      if (agent) agent.model = cli.model
    }
  }

  // Fallback: apply primary model to agents still without one
  if (primaryCli?.model) {
    for (const agent of agents) {
      if (!agent.model) {
        agent.model = primaryCli.model
      }
    }
  }
}

/**
 * Load the agent registry.
 *
 * Resolution order:
 *   1. $WORKSPACE_PATH/clawport/agents.json  (user's own config)
 *   2. Auto-discovered from $WORKSPACE_PATH   (agents/ directory scan)
 *      + merged with other workspaces from `openclaw agents list --json`
 *   3. CLI-only discovery (scans each agent's workspace)
 *   4. Bundled lib/agents.json               (default example registry)
 *
 * OpenClaw Dashboard agent registry loader.
 */
export function loadRegistry(): AgentEntry[] {
  if (_registryCache && Date.now() - _registryCache.ts < REGISTRY_CACHE_TTL) {
    return _registryCache.data
  }
  const data = _loadRegistryUncached()
  _registryCache = { data, ts: Date.now() }
  return data
}

function _loadRegistryUncached(): AgentEntry[] {
  const workspacePath = process.env.WORKSPACE_PATH
  const openclawBin = process.env.OPENCLAW_BIN

  if (workspacePath) {
    // 1. User-provided override
    const userRegistryPath = join(workspacePath, 'clawport', 'agents.json')
    if (existsSync(userRegistryPath)) {
      try {
        const raw = readFileSync(userRegistryPath, 'utf-8')
        return JSON.parse(raw) as AgentEntry[]
      } catch {
        // Malformed user JSON -- fall through
      }
    }

    // 2. Auto-discover from primary workspace filesystem
    const discovered = discoverAgents(workspacePath)

    // 2b. Enrich with CLI model data + merge other workspaces
    if (discovered && openclawBin) {
      const cliAgents = listCliAgents(openclawBin)
      if (cliAgents) {
        enrichModelsFromCli(discovered, cliAgents, workspacePath)
        if (cliAgents.length > 1) {
          return mergeExtraWorkspaces(discovered, cliAgents, workspacePath)
        }
      }
      return discovered
    }
    if (discovered) return discovered

    // 3. CLI-only: no primary workspace agents, scan each CLI agent's workspace
    if (openclawBin) {
      const cliAgents = listCliAgents(openclawBin)
      if (cliAgents) {
        return mergeExtraWorkspaces([], cliAgents, '')
      }
    }
  }

  // 4. Bundled fallback
  return (bundledRegistry as unknown) as AgentEntry[]
}
